### ISSUE TITLE
Whitelist possible?

### ISSUE THREAD

**Issue by patrickbolle** [omivore/monastery#1]
Hi!
Love this so far as Leechblock isn't going to work with 57+ 

I want to block reddit.com for example, but want to still keep being able to access certain subreddits like reddit.com/r/nhlstreams etc etc.

Would this be easy to add? 

Also, having a way to delay / put an obstacle in front of the user when we try and disable the plugin would be cool too. Just like stayfocusd

**Comment by omivore** [comment]
Ah, so I have an advantage over Leechblock after all!
I came across it after publishing monastery and felt very silly.

Anyway, I believe so, yes, a whitelist is possible. I have it almost ready - although the addon might have to go under review again so it might take a while to get to you.

As for the delay obstacle - do you make access to the addons disable page difficult? Or do you mean a delay page whenever a blacklisted page is accessed?

**Comment by omivore** [comment]
Well it's done but I'm going to add one more minor feature - and then see about both types of delay pages. Although perhaps I should push this change immediately? Probably not. Don't back to me on what type of delays you were talking about!

**Comment by patrickbolle** [comment]
Sweet!! Thanks so much. 

Not sure how difficult it is, but is the Web Extensions API easy for you to limit Monastery by time/date. For example, like how Leechblock does it - Monday - Friday from 9 - 5 I can only access Facebook, etc for 20 minutes.

I'm getting more into Firefox dev at the moment so maybe I will look into this as well so I can give ya a hand! Thanks!
