### ISSUE TITLE
Unable to update permitted time after it is set to zero

### ISSUE THREAD

**Issue by ezag** [omivore/monastery#10]
After setting blocking time to 0h 0m and saving settings, it's not possible to set it to another value (since "time is up for today").

**Comment by omivore** [comment]
Oh shoot that's true. Out of curiosity, what do you think should happen? Allowing the limit to be changed willy nilly just because sites are always blocked doesn't seem to make sense either.

**Comment by ezag** [comment]
@omivore Perhaps allow to increase the limit, but make the new value effective next day?

Anyway, until this is fixed, could you recommend a way to set **timeout** using debug tools (or just reset add-on's data completely)? I just want to use Delay Page feature, but after experimenting with setting timeout to 0 I can't.

**Comment by omivore** [comment]
Hmm the data is stored in the browser storage or however it's implemented, so the only recourse I can think of is just removing and adding it back. Sorry :/

**Comment by ezag** [comment]
@omivore already tried removing & adding back, but these settings are persistent. Also tried Storage tab in Web Console, but it shows only data for hosts in currently open tabs, but not add-ons. Thanks anyway!

**Comment by omivore** [comment]
The only option would be to delete your sync profile then remake it with the same email. I'll be honest, I'm not even sure if that would work. I guess you'll have to disable it until I figure out a good way to allow it to be changed. Again, apologies.
